# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Integration tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: w3af integration tests

    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        group: [1, 2, 3, 4]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pipenv'
    - name: Install Gtk
      run: sudo apt-get update && sudo apt-get install -y libgirepository1.0-dev gir1.2-gtk-3.0 libgtk-3-dev gir1.2-pango-1.0 libpango1.0-dev gir1.2-gtksource-4 libgtksourceview-4-dev libicu-dev gir1.2-webkit2-4.0 libwebkit2gtk-4.0-dev graphviz libssl-dev libffi-dev libsqlite3-dev libxml2-dev git
    - name: Install node packages
      run: npm install
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel
    - name: Install dependencies
      run: |
        pipenv install
    - name: Start docker containers
      run: |
        docker-compose -f w3af/tests/docker-compose.yml up
    - name: Integration tests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: |
          pipenv run pytest --cov=w3af --splits 4 --group ${{ matrix.group }} -m "moth and not git and not gui and not fails"
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage${{ matrix.group }}
        path: .coverage
