# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test w3af

    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        group: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: 'pipenv'
    - name: Install Gtk
      run: sudo apt-get update && sudo apt-get install -y libgirepository1.0-dev gir1.2-gtk-3.0 libgtk-3-dev gir1.2-pango-1.0 libpango1.0-dev gir1.2-gtksource-4 libgtksourceview-4-dev libicu-dev gir1.2-webkit2-4.0 libwebkit2gtk-4.0-dev graphviz libssl-dev libffi-dev libsqlite3-dev libxml2-dev git
    - name: Install node packages
      run: npm install
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel
    - name: Install dependencies
      run: |
        pipenv install
    - name: Core unittests
      uses: GabrielBB/xvfb-action@v1
      with:
        run: |
          pipenv run pytest --cov=w3af --splits 10 --group ${{ matrix.group }} -m "not moth and not fails and not git and not gui and not integration and not ci_ignore"
    - name: Upload coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage${{ matrix.group }}
        path: .coverage

  coverage:
    name: Upload coverage to codecov
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pipenv'
      - name: Install deps
        run: |
          python -m pip install --upgrade pipenv wheel
          pipenv install
      - name: Download all artifacts
        # Downloads coverage1, coverage2, etc.
        uses: actions/download-artifact@v2
      - name: Run coverage
        run: |
          coverage combine coverage*/.coverage*
          coverage report --fail-under=60
          coverage xml
      - name: "Upload coverage to Codecov"
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
