# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install Gtk
      run: sudo apt-get install -y libgirepository1.0-dev
    - name: Install pipenv
      run: |
        python -m pip install --upgrade pipenv wheel
    - name: Install dependencies
      run: |
        pipenv install
    - name: Core data unittests
      run: |
        pipenv run nosetests -A 'not moth and not internet and not fails and not git' -w ./w3af/core/data/
    - name: Core controllers unittests
      run: |
        pipenv run nosetests -A 'not moth and not internet and not fails and not git' -w ./w3af/core/controllers/

    name: Test w3af
